name: 'Veracode Fix for SCA'
description: ''
inputs:
  github-token:
    description: "Github token to download"
    required: true
  sca-scan-run-id:
    description: ""
    required: true
  sca-scan-artifact-id:
    description: ""
    required: true
  repository:
    description: ""
    required: true
  branch:
    description: ""
    required: true
  client-payload-token:
    description: ""
    required: true
  github-api-url:
    description: ""
    required: true
  pr-number:
    description: ""
    required: true
  vid:
    description: ""
    required: true
  vkey:
    description: ""
    required: true
  fix-sca-params:
    description: ""
    required: false

runs:
  using: "composite"
  steps:
  - name: Download SCA scan artifact
    uses: actions/download-artifact@v5
    with:
      github-token: ${{ inputs.github-token }}
      run-id: ${{ inputs.sca-scan-run-id }}
      artifact-ids: ${{ inputs.sca-scan-artifact-id }}

  - uses: actions/checkout@v4
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.branch }}
      token: ${{ inputs.client-payload-token }}
      path: 'source-code'

  # temporary step - will remove once Fix SCA changes are merged into Prod Release CLI
  - name: Setup Veracode CLI
    shell: bash
    env:
      ACTION_PATH: ${{ github.action_path }}
      FIX_SCA_VERACODE_API_KEY_ID: ${{ inputs.vid }}
      FIX_SCA_VERACODE_API_KEY_SECRET: ${{ inputs.vkey }}
    run: |
      bash ${{ github.action_path }}/scripts/fix-sca-setup-cli.sh

  - name: Setup ast-grep
    shell: bash
    run: |
      sudo unzip -q ${{ github.action_path }}/ast-grep/ast-grep-0.40.5.zip -d /usr/local/bin ast-grep

  - name: Run Fix for SCA
    id: run-fix-sca
    env:
      SCA_RESULTS_FILE_NAME: "scaResults.json"
      FIX_SCA_PARAMS: ${{ input.fix-sca-params }}
    shell: bash
    run: |
      bash ${{ github.action_path }}/scripts/fix-sca-run.sh

  - name: Create Pull Request
    id: create-pr
    env:
      SECRETS_PAT: ${{ inputs.github-token }}
      GITHUB_API_URL: ${{ inputs.github-api-url }}
      REPOSITORY_FULL_NAME: ${{ inputs.repository }}
      SOURCE_BRANCH: ${{ inputs. branch }}
      FIX_PR_COMMIT_MESSAGE: "Changes auto-generated by Veracode Fix for SCA "
      FIX_PR_BRANCH_PREFIX: "scafix"
    shell: bash
    if: steps.run-fix-sca.outputs.run-next-step == 'true'
    run: |
      bash ${{ github.action_path }}/scripts/fix-sca-create-pr.sh

  - name: Post Fix PR comment on original PR
    shell: bash
    env:
      SECRETS_PAT: ${{ inputs.github-token }}
      GITHUB_API_URL: ${{ inputs.github-api-url }}
      REPOSITORY_FULL_NAME: ${{ inputs.repository }}
      PR_NUMBER: ${{ inputs.pr-number }}
    if: steps.create-pr.outputs.run-next-step == 'true'
    run: |
      bash ${{ github.action_path }}/scripts/fix-sca-post-pr-comment.sh